version: "3"
services:
  master:
    image: redis:5.0
    container_name: redis-master-6300
    ports: 
      - 6300:6379
    command: redis-server /etc/redis/redis.conf #--appendonly yes
    volumes:
      - /D/coding-001/sky/sky-redisson/doc/1master3slave/redis-m.conf:/etc/redis/redis.conf 
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.11
  slave1:
    image: redis:5.0
    container_name: redis-slave-6301
    depends_on:
      - master
    ports:
      - 6301:6379
    # command: redis-server /etc/redis.conf --slaveof redis-master-8001 6379  # --appendonly yes
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /D/coding-001/sky/sky-redisson/doc/1master3slave/redis-s.conf:/etc/redis/redis.conf
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.12
  slave2:
    image: redis:5.0
    container_name: redis-slave-6302
    depends_on:
      - master
    ports:
      - 6302:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /D/coding-001/sky/sky-redisson/doc/1master3slave/redis-s.conf:/etc/redis/redis.conf
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.13
  slave3:
    image: redis:5.0
    container_name: redis-slave-6303
    depends_on:
      - master
    ports:
      - 6303:6379
    command: redis-server /etc/redis/redis.conf
    volumes:
      - /D/coding-001/sky/sky-redisson/doc/1master3slave/redis-s.conf:/etc/redis/redis.conf
    networks: 
      extnetwork:
        ipv4_address: 172.100.0.14

networks:
  extnetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/16
          gateway: 172.100.0.1
        